language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master
    - develop

script:
  - cd client
  - npm install
  - npm run test-ci
  - ng build --prod

notifications:
  email:
    on_failure: always
    on_success: always